format = """
$os\
$shell\
$sudo\
$username\
$hostname\
$directory\
$jobs\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$time\
$cmd_duration\
$line_break\
$character"""

continuation_prompt = 'â–¶â–¶ '

[character]
error_symbol = "[âœ—](bold red)"
success_symbol = "[âœ](bold green)"
vicmd_symbol = "[â®](green)"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[directory]
fish_style_pwd_dir_length = 5
read_only = " ó°Œ¾"
repo_root_style =  'green'
style = "blue"
truncate_to_repo = false
truncation_length = 4

[docker_context]
symbol = "ïŒˆ "

[env_var]
variable = "CURRENTSHELL"
default = "unknown"

[fill]
symbol = ' '
style = 'bold green'

[git_branch]
format = "[$branch]($style) "
style = "purple"
symbol = "ï˜ "

[git_commit]
tag_disabled = false

[git_metrics]
disabled = false

[git_status]
format = "[[(*$conflicted$untracked$renamed$deleted)](red)[($modified$staged)](218)[( $stashed)](165)( $ahead_behind)]($style)"
style = "cyan"
# conflicted = "â€‹"
# untracked = "â€‹"
# modified = "â€‹"
# staged = "â€‹"
# renamed = "â€‹"
# deleted = "â€‹"
stashed = "ğŸ¥"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
windows_starship = "/mnt/c/Program Files/starship/bin/starship.exe"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-red"

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hostname]
ssh_symbol = "ó°£€ "

[os]
# style is defined within the symbol
format = "$symbol "
disabled = false

[os.symbols]
Linux = "[ïŒš](bold purple)"
Macos = "[ïŒ‚](bold purple)"
Ubuntu = "[î¯‰](bold purple)"
Unknown = "ï’‰"
Windows = "[ó°¨¡](bold green)"

[rust]
symbol = "ïŒ£ "

[shell]
disabled = false
format = '[$indicator]($style) '
zsh_indicator = 'ó°°¶'
bash_indicator = 'î¯Š'
fish_indicator = 'ó°ˆº'

[sudo]
disabled = false

[time]
disabled = false
format = ' [$time](cyan)'
time_format = "%T %e-%b "
utc_time_offset = "local"
