format = """
$shell\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$time\
$cmd_duration\
$line_break\
$sudo\
$character"""

[env_var]
variable = "CURRENTSHELL"
default = "unknown"

[directory]
style = "blue"
truncate_to_repo = false
repo_root_style =  'green'
truncation_length = 4
fish_style_pwd_dir_length = 5

[character]
success_symbol = "[\\$](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[git_branch]
format = "[$branch]($style)"
style = "purple"

[git_status]
format = " [[(*$conflicted$untracked$renamed$deleted)](red)[($modified$staged)](218)[( $stashed)](165)( $ahead_behind)]($style) "
style = "cyan"
# conflicted = "â€‹"
# untracked = "â€‹"
# modified = "â€‹"
# staged = "â€‹"
# renamed = "â€‹"
# deleted = "â€‹"
stashed = "ğŸ¥"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[time]
disabled = false
format = '[\[$time\]](cyan)'
time_format = "%T %e-%b"
utc_time_offset = "local"

[shell]
disabled = false
format = '[$indicator]($style) '
zsh_indicator = 'ğŸ‡¿'
bash_indicator = 'ğŸ‘Š'
fish_indicator = 'ğŸŸ'

[sudo]
disabled = false